version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    image: docker.io/home-flow:latest
    container_name: home-flow-container
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - ./mcp:/usr/src/mcp
    extra_hosts:
      - host.docker.internal:host-gateway
    stdin_open: true