services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: home-flow-sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
    ports:
      - "19000:9000"
    init: true